export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
};

export const userConstants = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS"
};

export const updateUserConstants = {
    UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE"
}

export const profileConstants = {
    GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
    GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
    GET_PORIFLE_FAILURE: "GET_PORIFLE_FAILURE"
}

export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
    ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
    UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE"
}

export const courseConstants = {
    GET_ALL_COURSE_REQUEST: "GET_ALL_COURSE_REQUEST",
    GET_ALL_COURSE_SUCCESS: "GET_ALL_COURSE_SUCCESS",
    GET_ALL_COURSE_NUMBER_SUCCESS: "GET_ALL_COURSE_NUMBER_SUCCESS",
    GET_ALL_COURSE_FAILURE: "GET_ALL_COURSE_FAILURE",
    ADD_COURSE_REQUEST: "ADD_COURSE_REQUEST",
    ADD_COURSE_SUCCESS: "ADD_COURSE_SUCCESS",
    ADD_COURSE_FAILURE: "ADD_COURSE_FAILURE",
    DELETE_COURSE_REQUEST: "DELETE_COURSE_REQUEST",
    DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
    DELETE_COURSE_FAILURE: "DELETE_COURSE_FAILURE",
    DISABLE_COURSE_REQUEST: "DISABLE_COURSE_REQUEST",
    DISABLE_COURSE_SUCCESS: "DISABLE_COURSE_SUCCESS",
    DISABLE_COURSE_FAILURE: "DISABLE_COURSE_FAILURE",
    ENABLE_COURSE_REQUEST: "ENABLE_COURSE_REQUEST",
    ENABLE_COURSE_SUCCESS: "ENABLE_COURSE_SUCCESS",
    ENABLE_COURSE_FAILURE: "ENABLE_COURSE_FAILURE",
    GET_COURSE_DETAIL_REQUEST: "GET_COURSE_DETAIL_REQUEST",
    GET_COURSE_DETAIL_SUCCESS: "GET_COURSE_DETAIL_SUCCESS",
    GET_COURSE_DETAIL_ERR_SUCCESS: "GET_COURSE_DETAIL_ERR_SUCCESS",
    GET_COURSE_DEATIL_FAILURE: "GET_COURSE_DEATIL_FAILURE"
}


export const courseContentConstants = {
    GET_ALL_COURSE_CONTENT_REQUEST: "GET_ALL_COURSE_CONTENT_REQUEST",
    GET_ALL_COURSE_CONTENT_SUCCESS: "GET_ALL_COURSE_CONTENT_SUCCESS",
    GET_ALL_COURSE_CONTENT_FAILURE: "GET_ALL_COURSE_CONTENT_FAILURE",
    ADD_COURSE_CONTENT_REQUEST: "ADD_COURSE_CONTENT_REQUEST",
    ADD_COURSE_CONTENT_SUCCESS: "ADD_COURSE_CONTENT_SUCCESS",
    ADD_COURSE_CONTENT_FAILURE: "ADD_COURSE_CONTENT_FAILURE"
}

export const profsConstants = {
    GET_PROFS_REQUEST: "GET_PROFS_REQUEST",
    GET_PROFS_SUCCESS: "GET_PROFS_SUCCESS",
    GET_PROFS_FAILURE: "GET_PROFS_FAILURE",
    GET_PROFS_NUMBER_SUCCESS: "GET_PROFS_NUMBER_SUCCESS",
    ACTIVE_PROFS_REQUEST: "ACTIVE_PROFS_REQUEST",
    ACTIVE_PROFS_SUCCESS: "ACTIVE_PROFS_SUCCESS",
    ACTIVE_PROFS_FAILURE: "ACTIVE_PROFS_FAILURE",
    REJECT_PROFS_REQUEST: "REJECT_PROFS_REQUEST",
    REJECT_PROFS_SUCCESS: "REJECT_PROFS_SUCCESS",
    REJECT_PROFS_FAILURE: "REJECT_PROFS_FAILURE"
}

export const adminsConstants = {
    GET_ADMIN_REQUEST: "GET_ADMIN_REQUEST",
    GET_ADMIN_SUCCESS: "GET_ADMIN_SUCCESS",
    GET_ADMIN_FAILURE: "GET_ADMIN_FAILURE",
    GET_ADMIN_NUMBER_SUCCESS: "GET_ADMIN_NUMBER_SUCCESS",
    ADD_ADMIN_REQUEST: "ADD_ADMIN_REQUEST",
    ADD_ADMIN_SUCCESS: "ADD_ADMIN_SUCCESS",
    ADD_ADMIN_FAILURE: "ADD_ADMIN_FAILURE"
}


export const bannerConstants = {
    GET_BANNERS_REQUEST: "GET_BANNERS_REQUEST",
    GET_BANNERS_SUCCESS: "GET_BANNERS_SUCCESS",
    GET_BANNERS_FAILURE: "GET_BANNERS_FAILURE",
    UPDATE_BANNERS_REQUEST: "UPDATE_BANNERS_REQUEST",
    UPDATE_BANNERS_SUCCESS: "UPDATE_BANNERS_SUCCESS",
    UPDATE_BANNERS_FAILURE: "UPDATE_BANNERS_FAILURE"
}

export const aboutIntroConstants = {
    GET_ABOUT_INTRO_REQUEST: "GET_ABOUT_INTRO_REQUEST",
    GET_ABOUT_INTRO_SUCCESS: "GET_ABOUT_INTRO_SUCCESS",
    GET_ABOUT_INTRO_FAILURE: "GET_ABOUT_INTRO_FAILURE",
    UPDATE_ABOUT_INTRO_REQUEST: "UPDATE_ABOUT_INTRO_REQUEST",
    UPDATE_ABOUT_INTRO_SUCCESS: "UPDATE_ABOUT_INTRO_SUCCESS",
    UPDATE_ABOUT_INTRO_FAILURE: "UPDATE_ABOUT_INTRO_FAILURE"
}

export const actionConstants = {
    GET_ACTION_REQUEST: "GET_ACTION_REQUEST",
    GET_ACTION_SUCCESS: "GET_ACTION_SUCCESS",
    GET_ACTION_FAILURE: "GET_ACTION_FAILURE",
    UPDATE_ACTION_REQUEST: "UPDATE_ACTION_REQUEST",
    UPDATE_ACTION_SUCCESS: "UPDATE_ACTION_SUCCESS",
    UPDATE_ACTION_FAILURE: "UPDATE_ACTION_FAILURE"
}

export const actionContentConstants = {
    GET_ACTION_CONTENT_REQUEST: "GET_ACTION_CONTENT_REQUEST",
    GET_ACTION_CONTENT_SUCCESS: "GET_ACTION_CONTENT_SUCCESS",
    GET_ACTION_CONTENT_FAILURE: "GET_ACTION_CONTENT_FAILURE",
    UPDATE_ACTION_CONTENT_REQUEST: "UPDATE_ACTION_CONTENT_REQUEST",
    UPDATE_ACTION_CONTENT_SUCCESS: "UPDATE_ACTION_CONTENT_SUCCESS",
    UPDATE_ACTION_CONTENT_FAILURE: "UPDATE_ACTION_CONTENT_FAILURE"
}

export const historyAboutConstants = {
    GET_ABOUT_INTRO_REQUEST: "GET_ABOUT_INTRO_REQUEST",
    GET_HISTORY_ABOUT_SUCCESS: "GET_HISTORY_ABOUT_SUCCESS",
    GET_ABOUT_INTRO_FAILURE: "GET_ABOUT_INTRO_FAILURE",
    UPDATE_ABOUT_INTRO_REQUEST: "UPDATE_ABOUT_INTRO_REQUEST",
    UPDATE_ABOUT_INTRO_SUCCESS: "UPDATE_ABOUT_INTRO_SUCCESS",
    UPDATE_ABOUT_INTRO_FAILURE: "UPDATE_ABOUT_INTRO_FAILURE"
}

export const donationConstants = {
    GET_ABOUT_INTRO_REQUEST: "GET_ABOUT_INTRO_REQUEST",
    GET_DONATION_SUCCESS: "GET_DONATION_SUCCESS",
    GET_ABOUT_INTRO_FAILURE: "GET_ABOUT_INTRO_FAILURE",
    UPDATE_ABOUT_INTRO_REQUEST: "UPDATE_ABOUT_INTRO_REQUEST",
    UPDATE_ABOUT_INTRO_SUCCESS: "UPDATE_ABOUT_INTRO_SUCCESS",
    UPDATE_ABOUT_INTRO_FAILURE: "UPDATE_ABOUT_INTRO_FAILURE"
}

export const sponsorConstants = {
    GET_SPONSOR_REQUEST: "GET_SPONSOR_REQUEST",
    GET_SPONSOR_SUCCESS: "GET_SPONSOR_SUCCESS",
    GET_SPONSOR_FAILURE: "GET_SPONSOR_FAILURE",
    UPDATE_SPONSOR_REQUEST: "UPDATE_SPONSOR_REQUEST",
    UPDATE_SPONSOR_SUCCESS: "UPDATE_SPONSOR_SUCCESS",
    UPDATE_SPONSOR_FAILURE: "UPDATE_SPONSOR_FAILURE",
    ADD_SPONSOR_REQUEST: "ADD_SPONSOR_REQUEST",
    ADD_SPONSOR_SUCCESS: "ADD_SPONSOR_SUCCESS",
    ADD_SPONSOR_FAILURE: "ADD_SPONSOR_FAILURE",
    DELETE_SPONSOR_REQUEST: "DELETE_SPONSOR_REQUEST",
    DELETE_SPONSOR_SUCCESS: "DELETE_SPONSOR_SUCCESS",
    DELETE_SPONSOR_FAILURE: "DELETE_SPONSOR_FAILURE"
}

export const testimonialConstants = {
    GET_ABOUT_INTRO_REQUEST: "GET_ABOUT_INTRO_REQUEST",
    GET_TESTIMONIAL_SUCCESS: "GET_TESTIMONIAL_SUCCESS",
    GET_ABOUT_INTRO_FAILURE: "GET_ABOUT_INTRO_FAILURE",
    UPDATE_ABOUT_INTRO_REQUEST: "UPDATE_ABOUT_INTRO_REQUEST",
    UPDATE_ABOUT_INTRO_SUCCESS: "UPDATE_ABOUT_INTRO_SUCCESS",
    UPDATE_ABOUT_INTRO_FAILURE: "UPDATE_ABOUT_INTRO_FAILURE"
}

export const brandImageConstants = {
    GET_BRAND_IMAGE_REQUEST: "GET_BRAND_IMAGE_REQUEST",
    GET_BRAND_IMAGE_SUCCESS: "GET_BRAND_IMAGE_SUCCESS",
    GET_BRAND_IMAGE_FAILURE: "GET_BRAND_IMAGE_FAILURE",
    UPDATE_BRAND_IMAGE_REQUEST: "UPDATE_BRAND_IMAGE_REQUEST",
    UPDATE_BRAND_IMAGE_SUCCESS: "UPDATE_BRAND_IMAGE_SUCCESS",
    UPDATE_BRAND_IMAGE_FAILURE: "UPDATE_BRAND_IMAGE_FAILURE"
}

export const homeHeaderConstants = {
    GET_HOME_HEADER_REQUEST: "GET_HOME_HEADER_REQUEST",
    GET_HOME_HEADER_SUCCESS: "GET_HOME_HEADER_SUCCESS",
    GET_HOME_HEADER_FAILURE: "GET_HOME_HEADER_FAILURE",
    UPDATE_HOME_HEADER_REQUEST: "UPDATE_HOME_HEADER_REQUEST",
    UPDATE_HOME_HEADER_SUCCESS: "UPDATE_HOME_HEADER_SUCCESS",
    UPDATE_HOME_HEADER_FAILURE: "UPDATE_HOME_HEADER_FAILURE"
}

export const topSubjectConstants = {
    GET_ABOUT_INTRO_REQUEST: "GET_ABOUT_INTRO_REQUEST",
    GET_TOP_SUBJECT_SUCCESS: "GET_TOP_SUBJECT_SUCCESS",
    GET_ABOUT_INTRO_FAILURE: "GET_ABOUT_INTRO_FAILURE",
    UPDATE_ABOUT_INTRO_REQUEST: "UPDATE_ABOUT_INTRO_REQUEST",
    UPDATE_ABOUT_INTRO_SUCCESS: "UPDATE_ABOUT_INTRO_SUCCESS",
    UPDATE_ABOUT_INTRO_FAILURE: "UPDATE_ABOUT_INTRO_FAILURE"
}

export const topSubjectTitleConstants = {
    GET_TOP_SUBJECT_TITLE_REQUEST: "GET_TOP_SUBJECT_TITLE_REQUEST",
    GET_TOP_SUBJECT_TITLE_SUCCESS: "GET_TOP_SUBJECT_TITLE_SUCCESS",
    GET_TOP_SUBJECT_TITLE_FAILURE: "GET_TOP_SUBJECT_TITLE_FAILURE",
    UPDATE_TOP_SUBJECT_TITLE_REQUEST: "UPDATE_TOP_SUBJECT_TITLE_REQUEST",
    UPDATE_TOP_SUBJECT_TITLE_SUCCESS: "UPDATE_TOP_SUBJECT_TITLE_SUCCESS",
    UPDATE_TOP_SUBJECT_TITLE_FAILURE: "UPDATE_TOP_SUBJECT_TITLE_FAILURE"
}

export const blogTitleConstants = {
    GET_BLOG_TITLE_REQUEST: "GET_BLOG_TITLE_REQUEST",
    GET_BLOG_TITLE_SUCCESS: "GET_BLOG_TITLE_SUCCESS",
    GET_BLOG_TITLE_FAILURE: "GET_BLOG_TITLE_FAILURE",
    UPDATE_BLOG_TITLE_REQUEST: "UPDATE_BLOG_TITLE_REQUEST",
    UPDATE_BLOG_TITLE_SUCCESS: "UPDATE_BLOG_TITLE_SUCCESS",
    UPDATE_BLOG_TITLE_FAILURE: "UPDATE_BLOG_TITLE_FAILURE",
}

export const profsTitleConstants = {
    GET_PROFS_TITLE_REQUEST: "GET_PROFS_TITLE_REQUEST",
    GET_PROFS_TITLE_SUCCESS: "GET_PROFS_TITLE_SUCCESS",
    GET_PROFS_TITLE_FAILURE: "GET_PROFS_TITLE_FAILURE",
    UPDATE_PROFS_TITLE_REQUEST: "UPDATE_PROFS_TITLE_REQUEST",
    UPDATE_PROFS_TITLE_SUCCESS: "UPDATE_PROFS_TITLE_SUCCESS",
    UPDATE_PROFS_TITLE_FAILURE: "UPDATE_PROFS_TITLE_FAILURE",
}

export const sponsorsTitleConstants = {
    GET_SPONSORS_TITLE_REQUEST: "GET_SPONSORS_TITLE_REQUEST",
    GET_SPONSORS_TITLE_SUCCESS: "GET_SPONSORS_TITLE_SUCCESS",
    GET_SPONSORS_TITLE_FAILURE: "GET_SPONSORS_TITLE_FAILURE",
    UPDATE_SPONSORS_TITLE_REQUEST: "UPDATE_SPONSORS_TITLE_REQUEST",
    UPDATE_SPONSORS_TITLE_SUCCESS: "UPDATE_SPONSORS_TITLE_SUCCESS",
    UPDATE_SPONSORS_TITLE_FAILURE: "UPDATE_SPONSORS_TITLE_FAILURE",
}

export const blogConstants = {
    GET_BLOG_REQUEST: "GET_BLOG_REQUEST",
    GET_BLOG_SUCCESS: "GET_BLOG_SUCCESS",
    GET_BLOG_FAILURE: "GET_BLOG_FAILURE",
    GET_BLOG_DETAIL_REQUEST: "GET_BLOG_DETAIL_REQUEST",
    GET_BLOG_DETAIL_SUCCESS: "GET_BLOG_DETAIL_SUCCESS",
    GET_BLOG_DETAIL_FAILURE: "GET_BLOG_DETAIL_FAILURE",
    DELETE_BLOG_REQUEST: "DELETE_BLOG_REQUEST",
    DELETE_BLOG_SUCCESS: "DELETE_BLOG_SUCCESS",
    DELETE_BLOG_FAILURE: "DELETE_BLOG_FAILURE",
    UPDATE_BLOG_REQUEST: "UPDATE_BLOG_REQUEST",
    UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
    UPDATE_BLOG_FAILURE: "UPDATE_BLOG_FAILURE",
    ADD_BLOG_REQUEST: "ADD_BLOG_REQUEST",
    ADD_BLOG_SUCCESS: "ADD_BLOG_SUCCESS",
    ADD_BLOG_FAILURE: "ADD_BLOG_FAILURE"
}

export const coursTitleConstants = {
    GET_COURS_TITLE_REQUEST: "GET_COURS_TITLE_REQUEST",
    GET_COURS_TITLE_SUCCESS: "GET_COURS_TITLE_SUCCESS",
    GET_COURS_TITLE_FAILURE: "GET_COURS_TITLE_FAILURE",
    UPDATE_COURS_TITLE_REQUEST: "UPDATE_COURS_TITLE_REQUEST",
    UPDATE_COURS_TITLE_SUCCESS: "UPDATE_COURS_TITLE_SUCCESS",
    UPDATE_COURS_TITLE_FAILURE: "UPDATE_COURS_TITLE_FAILURE"
}

export const whyLearnConstants = {
    GET_WHY_LEARN_REQUEST: "GET_WHY_LEARN_REQUEST",
    GET_WHY_LEARN_SUCCESS: "GET_WHY_LEARN_SUCCESS",
    GET_WHY_LEARN_FAILURE: "GET_WHY_LEARN_FAILURE",
    UPDATE_WHY_LEARN_REQUEST: "UPDATE_WHY_LEARN_REQUEST",
    UPDATE_WHY_LEARN_SUCCESS: "UPDATE_WHY_LEARN_SUCCESS",
    UPDATE_WHY_LEARN_FAILURE: "UPDATE_WHY_LEARN_FAILURE"
}

export const whyLearnIntroConstants = {
    GET_WHY_LEARN_INTRO_REQUEST: "GET_WHY_LEARN_INTRO_REQUEST",
    GET_WHY_LEARN_INTRO_SUCCESS: "GET_WHY_LEARN_INTRO_SUCCESS",
    GET_WHY_LEARN_INTRO_FAILURE: "GET_WHY_LEARN_INTRO_FAILURE",
    UPDATE_WHY_LEARN_INTRO_REQUEST: "UPDATE_WHY_LEARN_INTRO_REQUEST",
    UPDATE_WHY_LEARN_INTRO_SUCCESS: "UPDATE_WHY_LEARN_INTRO_SUCCESS",
    UPDATE_WHY_LEARN_INTRO_FAILURE: "UPDATE_WHY_LEARN_INTRO_FAILURE"
}

export const whyTeachConstants = {
    GET_WHY_TEACH_REQUEST: "GET_WHY_TEACH_REQUEST",
    GET_WHY_TEACH_SUCCESS: "GET_WHY_TEACH_SUCCESS",
    GET_WHY_TEACH_FAILURE: "GET_WHY_TEACH_FAILURE",
    UPDATE_WHY_TEACH_REQUEST: "UPDATE_WHY_TEACH_REQUEST",
    UPDATE_WHY_TEACH_SUCCESS: "UPDATE_WHY_TEACH_SUCCESS",
    UPDATE_WHY_TEACH_FAILURE: "UPDATE_WHY_TEACH_FAILURE"
}

export const whyTeachIntroConstants = {
    GET_WHY_TEACH_INTRO_REQUEST: "GET_WHY_TEACH_INTRO_REQUEST",
    GET_WHY_TEACH_INTRO_SUCCESS: "GET_WHY_TEACH_INTRO_SUCCESS",
    GET_WHY_TEACH_INTRO_FAILURE: "GET_WHY_TEACH_INTRO_FAILURE",
    UPDATE_WHY_TEACH_INTRO_REQUEST: "UPDATE_WHY_TEACH_INTRO_REQUEST",
    UPDATE_WHY_TEACH_INTRO_SUCCESS: "UPDATE_WHY_TEACH_INTRO_SUCCESS",
    UPDATE_WHY_TEACH_INTRO_FAILURE: "UPDATE_WHY_TEACH_INTRO_FAILURE"
}

export const addressConstants = {
    GET_ADDRESS_REQUEST: "GET_ADDRESS_REQUEST",
    GET_ADDRESS_SUCCESS: "GET_ADDRESS_SUCCESS",
    GET_ADDRESS_FAILURE: "GET_ADDRESS_FAILURE",
    UPDATE_CONTACT_REQUEST: "UPDATE_CONTACT_REQUEST",
    UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
    UPDATE_CONTACT_FAILURE: "UPDATE_CONTACT_FAIRE"
}

export const logoAndDescConstants = {
    GET_LOGO_AND_DESC_REQUEST: "GET_LOGO_AND_DESC_REQUEST",
    GET_LOGO_AND_DESC_SUCCESS: "GET_LOGO_AND_DESC_SUCCESS",
    GET_LOGO_AND_DESC_FAILURE: "GET_LOGO_AND_DESC_FAILURE",
    UPDATE_LOGO_AND_DESC_REQUEST: "UPDATE_LOGO_AND_DESC_REQUEST",
    UPDATE_LOGO_AND_DESC_SUCCESS: "UPDATE_LOGO_AND_DESC_SUCCESS",
    UPDATE_LOGO_AND_DESC_FAILURE: "UPDATE_LOGO_AND_DESC_FAILURE"
}